data:extend {
    {
        type = "string-setting",
        name = "TimeControl-display",
        setting_type = "runtime-per-user",
        order = 100,
        default_value = 'when-warping',
        allowed_values = { 'never', 'when-warping', 'always' },
    },
    {
        type = "string-setting",
        name = "TimeControl-access",
        setting_type = "runtime-global",
        order = 101,
        default_value = 'admins',
        allowed_values = { 'admins', 'everyone' },
    },
    {
        type = "int-setting",
        name = "TimeControl-max-speed",
        setting_type = "runtime-global",
        order = 102,
        default_value = 64,
        minimum_value = 2,
        maximum_value = 128,
    },
    {
        type = "double-setting",
        name = "TimeControl-min-speed",
        setting_type = "runtime-global",
        order = 103,
        default_value = 0.125,
        minimum_value = 0.00000001,
        maximum_value = 0.99999999,
    },
    {
      type = "double-setting",
      name = "TimeControl-max-speed-multiplier",
      setting_type = "runtime-global",
      order = 104,
      default_value = 2,
      minimum_value = 2,
      maximum_value = 8,
  },
  {
      type = "double-setting",
      name = "TimeControl-min-speed-multiplier",
      setting_type = "runtime-global",
      order = 105,
      default_value = 0.5,
      minimum_value = 0.25,
      maximum_value = 1.0,
  },
}
